import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

const stationPageSource = readFileSync(new URL("../client/src/pages/StationPage.tsx", import.meta.url), "utf8");
const samplingPageSource = readFileSync(new URL("../client/src/pages/SamplingPage.tsx", import.meta.url), "utf8");
const importPageSource = readFileSync(new URL("../client/src/pages/ImportPage.tsx", import.meta.url), "utf8");
const operationsPageSource = readFileSync(new URL("../client/src/pages/OperationsPage.tsx", import.meta.url), "utf8");
const adminPageSource = readFileSync(new URL("../client/src/pages/AdminPage.tsx", import.meta.url), "utf8");
const engineerKpiPageSource = readFileSync(new URL("../client/src/pages/EngineerKpiPage.tsx", import.meta.url), "utf8");
const managementAccessSource = readFileSync(new URL("../client/src/lib/managementAccess.ts", import.meta.url), "utf8");
const dbSource = readFileSync(new URL("../server/db.ts", import.meta.url), "utf8");

describe("warehouse workflow pages", () => {
  it("exposes file upload import workflow and shared batch fields on the import page", () => {
    expect(importPageSource).toContain('title="匯入作業"');
    expect(importPageSource).toContain("trpc.station.importBatch.useMutation");
    expect(importPageSource).toContain("trpc.station.productNameOptions.useQuery");
    expect(importPageSource).toContain('enabled: canAccessManagementOps && rows.length > 0');
    expect(importPageSource).toContain('enabled: canAccessManagementOps');
    expect(importPageSource).toContain('shouldEnableManagementQuery');
    expect(importPageSource).toContain('shouldRedirectFromManagementOps');
    expect(importPageSource).toContain('allowedRoles: [...MANAGEMENT_VIEWER_ROLES]');
    expect(importPageSource).toContain('useAuth({ redirectOnUnauthenticated: true })');
    expect(importPageSource).toContain('setLocation("/operations")');
    expect(importPageSource).not.toContain("trpc.station.productCategoryOptions.useQuery");
    expect(importPageSource).toContain("CSV 檔案上傳");
    expect(importPageSource).toContain("選擇 CSV");
    expect(importPageSource).toContain("下載範例");
    expect(importPageSource).toContain("/manus-storage/import-products-example_756ddafb.csv");
    expect(importPageSource).toContain("廠商、商品分類、品牌、商品批號、商品序號、IMEI、品名");
    expect(importPageSource).toContain("系統會讀取檔案中的廠商、商品分類與品牌原文");
    expect(importPageSource).not.toContain("category,batchNo,serialNumber,imei,productName");
    expect(importPageSource).toContain("廠商（必填）");
    expect(importPageSource).toContain("到貨時間（同批共用）");
    expect(importPageSource).toContain("PO 單號（留空自動生成）");
    expect(importPageSource).toContain("const pendingA1Query = trpc.station.detail.useQuery(");
    expect(importPageSource).toContain('    { stationCode: "A1" },');
    expect(importPageSource).toContain("      retry: shouldRetryTransientQuery,");
    expect(importPageSource).toContain("已匯入未完成點貨的採購單");
    expect(importPageSource).toContain("採購單號");
    expect(importPageSource).toContain("商品類別 × 品牌");
    expect(importPageSource).toContain("總數量");
    expect(importPageSource).toContain("toggleSummaryRow");
    expect(importPageSource).toContain("ChevronDown");
    expect(importPageSource).toContain("ChevronRight");
    expect(importPageSource).toContain("目前沒有已匯入且尚未完成 A1 點貨的採購單");
    expect(importPageSource).toContain("請先填寫廠商名稱後再匯入");
    expect(importPageSource).toContain("目前沒有可匯入的資料");
    expect(importPageSource).toContain("尚未補齊必要欄位");
    expect(importPageSource).toContain("handleImport");
    expect(importPageSource).toContain("toast.error(importValidationMessage)");
    expect(importPageSource).toContain("toast.warning(`已載入");
    expect(importPageSource).toContain("商品分類（必填）");
    expect(importPageSource).toContain("品牌（必填）");
    expect(importPageSource).toContain("parseImportedCsvContent");
    expect(importPageSource).toContain("handleFileUpload");
    expect(importPageSource).toContain("目前已載入");
    expect(importPageSource).toContain("LARGE_IMPORT_PREVIEW_LIMIT");
    expect(importPageSource).toContain("showAllRows");
    expect(importPageSource).toContain("visibleRows");
    expect(importPageSource).toContain("import-product-name-options");
    expect(importPageSource).toContain("仍要顯示全部資料列");
    expect(importPageSource).toContain("為避免瀏覽器因大量欄位與品名選項同時渲染而無回應");
    expect(importPageSource.indexOf("CSV 檔案上傳")).toBeLessThan(importPageSource.indexOf("已載入資料預覽"));
  });

  it("provides A1 scan-to-complete fields and pending category summary on the station page", () => {
    expect(stationPageSource).toContain('stationCode === "A1"');
    expect(stationPageSource).toContain("目前待點貨商品分類與數量");
    expect(stationPageSource).toContain("商品分類 × 品牌");
    expect(stationPageSource).toContain("待點貨總數");
    expect(stationPageSource).toContain("待點貨數量");
    expect(stationPageSource).toContain("pendingCategorySummary");
    expect(stationPageSource).toContain("待入庫表格清單");
    expect(stationPageSource).toContain("最近自動移除待入庫");
    expect(stationPageSource).toContain("recentAutoRemovedStockItems");
    expect(stationPageSource).toContain("handleExportStockCsv");
    expect(stationPageSource).toContain("匯出 CSV");
    expect(stationPageSource).toContain("目前共有 <span className=\"font-semibold text-slate-900\">{filteredTasks.length}</span> 筆待入庫商品");
    expect(stationPageSource).toContain("task.brandName ?? task.importedBrandName ?? \"\"");
    expect(stationPageSource).toContain("A1 點到貨新增／補齊");
    expect(stationPageSource).not.toContain("廠商（必填）");
    expect(stationPageSource).toContain("商品批號");
    expect(stationPageSource).toContain("商品序號");
    expect(stationPageSource).toContain("IMEI");
    expect(stationPageSource).toContain("trpc.station.receive.useMutation");
    expect(stationPageSource).toContain("trpc.station.productNameOptions.useQuery");
    expect(stationPageSource).toContain("trpc.station.productCategoryOptions.useQuery");
    expect(stationPageSource).toContain('const MANAGEMENT_VIEWER_ROLES = ["supervisor", "manager", "admin"]');
    expect(stationPageSource).toContain('const shouldLoadProductNameOptions = stationCode === "A1" && (productNamePickerOpen || Boolean(arrivalForm.productName.trim()))');
    expect(stationPageSource).toContain('enabled: shouldLoadProductNameOptions');
    expect(stationPageSource).toContain('enabled: canEditCategory && Boolean(categoryDialogTask)');
    expect(stationPageSource).toContain("trpc.station.assignCategory.useMutation");
    expect(stationPageSource).toContain('const canEditCategory = stationCode === "A1" || stationCode === "C"');
    expect(stationPageSource).toContain("if (!canEditCategory) {");
    expect(stationPageSource).toContain('{canEditCategory ? <th className="px-4 py-3 text-right">操作</th> : null}');
    expect(stationPageSource).toContain("編輯品類設定");
    expect(stationPageSource).toContain("openCategoryEditor(task)");
    expect(stationPageSource).toContain("A1 改為掃碼補齊模式");
    expect(stationPageSource).toContain("輸入品名關鍵字搜尋（可選）");
    expect(stationPageSource).toContain("完成 A1 並準備下一筆");
    expect(stationPageSource).toContain("留在本頁");
  });

  it("supports A2 scan-to-complete workflow on the station page", () => {
    expect(stationPageSource).toContain('stationCode === "A2"');
    expect(stationPageSource).toContain('const canEditCategory = stationCode === "A1" || stationCode === "C"');
    expect(stationPageSource).toContain("submitA2ScanComplete");
    expect(stationPageSource).toContain("handleStationScanInputKey");
    expect(stationPageSource).toContain("掃描商品批號 QR 後可直接按 Enter 完成 A2");
    expect(stationPageSource).toContain("A2 已改為掃碼快速完工模式");
    expect(stationPageSource).toContain("A2 已完成並推進下一站，請直接掃描下一筆");
  });

  it("renders B and C option menu sections on the station page", () => {
    expect(stationPageSource).toContain("B 站故障狀態");
    expect(stationPageSource).toContain("電池檢測");
    expect(stationPageSource).toContain("電池膨脹");
    expect(stationPageSource).toContain("副廠電池");
    expect(stationPageSource).toContain("電池異常");
    expect(stationPageSource).toContain("例如：88、85%、待更換");
    expect(stationPageSource).toContain("完成軟體測試並推進下一站");
    expect(stationPageSource).toContain("B 站軟體測試完成");
    expect(stationPageSource).toContain("B 站故障狀態（C 站可修改）");
    expect(stationPageSource).toContain("這裡先帶入 B 站完成後的文字結果");
    expect(stationPageSource).toContain("修改故障狀態");
    expect(stationPageSource).toContain("isEditingBFaults");
    expect(stationPageSource).toContain("setBFaultEditing");
    expect(stationPageSource).toContain("C 站螢幕狀態");
    expect(stationPageSource).toContain("C 站機身外觀");
    expect(stationPageSource).toContain("C 站鏡頭狀態");
    expect(stationPageSource).toContain("bFaultOptionIds");
    expect(stationPageSource).toContain("faultOptionIds");
    expect(stationPageSource).toContain("appearanceOptionIds");
    expect(stationPageSource).toContain("cameraOptionIds");
    expect(stationPageSource).toContain("batteryIssueLabels");
    expect(stationPageSource).toContain("batteryNote");
    expect(stationPageSource).toContain("summarizeTextResult");
    expect(stationPageSource).toContain("是否修改電池／非螢幕功能狀態");
  });

  it("keeps the pending stock mismatch admin nav entry consistent across management pages", () => {
    const pendingMismatchNavEntry = '{ label: "待入庫待比對", path: "/admin/pending-stock-mismatches", icon: ShieldAlert, allowedRoles: ["admin"] }';

    expect(importPageSource).toContain(pendingMismatchNavEntry);
    expect(samplingPageSource).toContain(pendingMismatchNavEntry);
    expect(stationPageSource).toContain(pendingMismatchNavEntry);
    expect(adminPageSource).toContain(pendingMismatchNavEntry);
    expect(engineerKpiPageSource).toContain(pendingMismatchNavEntry);
    expect(engineerKpiPageSource).toContain('{ label: "匯入作業", path: "/import", icon: PackagePlus, allowedRoles: MANAGEMENT_VIEWER_ROLES }');
  });

  it("exposes inventory history from sidebar sub navigation and real backend movement fields", () => {
    expect(adminPageSource).toContain('label: "庫存異動紀錄", path: "/admin/inventory-history"');
    expect(adminPageSource).toContain('const activeAdminSection = resolveAdminSectionId(location);');
    expect(adminPageSource).toContain('product.inventoryMovement.importedOperatorName');
    expect(adminPageSource).toContain('product.inventoryMovement.pendingStockOperatorName');
    expect(adminPageSource).toContain('product.inventoryMovement.stockedOperatorName');
    expect(dbSource).toContain('await db.insert(stationEvents).values(importEventInserts);');
    expect(dbSource).toContain('event.stationCode === "A1" && event.eventType === "enter").at(-1)');
    expect(dbSource).toContain('event.stationCode === "STOCK" && event.eventType === "stock_ready").at(-1)');
  });

  it("includes category edit controls on the sampling page", () => {
    expect(samplingPageSource).toContain("trpc.station.productCategoryOptions.useQuery");
    expect(samplingPageSource).toContain('shouldEnableManagementQuery');
    expect(samplingPageSource).toContain('shouldRedirectFromManagementOps');
    expect(samplingPageSource).toContain('enabled: canAccessManagementOps,');
    expect(samplingPageSource).toContain('enabled: canAccessManagementOps && Boolean(categoryDialogTask)');
    expect(samplingPageSource).toContain('useAuth({ redirectOnUnauthenticated: true })');
    expect(samplingPageSource).toContain('setLocation("/operations")');
    expect(samplingPageSource).toContain("trpc.station.assignCategory.useMutation");
    expect(samplingPageSource).toContain("編輯品類設定");
    expect(samplingPageSource).toContain("openCategoryEditor(task)");
    expect(samplingPageSource).toContain("setCategoryDialogTask(task);");
    expect(samplingPageSource).toContain("選擇品類設定");
    expect(samplingPageSource).toContain("PackagePlus");
    expect(samplingPageSource).toContain("Undo2");
    expect(samplingPageSource).toContain("Search");
    expect(samplingPageSource).toContain("搜尋商品批號或商品序號");
    expect(samplingPageSource).toContain("relative max-w-xl space-y-3");
    expect(samplingPageSource).toContain("grid gap-3 md:grid-cols-2 xl:grid-cols-3");
    expect(samplingPageSource).toContain("編輯品類設定");
    expect(samplingPageSource).toContain("justify-end gap-3");
    expect(samplingPageSource).toContain("匯入作業");
    expect(samplingPageSource).toContain("返回站點總覽");
  });

  it("keeps management access rules and performance optimizations in shared modules", () => {
    expect(managementAccessSource).toContain('export const MANAGEMENT_VIEWER_ROLES = ["supervisor", "manager", "admin"] as const');
    expect(managementAccessSource).toContain('export function shouldEnableManagementQuery');
    expect(managementAccessSource).toContain('export function shouldRedirectFromManagementOps');
    expect(operationsPageSource).toContain('staleTime: 60_000');
    expect(operationsPageSource).toContain('gcTime: 5 * 60_000');
    expect(dbSource).toContain('let lastEnsureMvpSeedDataAt = 0');
    expect(dbSource).toContain('let lastArchiveExpiredDataAt = 0');
    expect(dbSource).toContain('recentAutoRemovedStockItems');
    expect(dbSource).toContain('includes("自動移除待入庫")');
    expect(dbSource).toContain('Date.now() - lastEnsureMvpSeedDataAt < 60_000');
    expect(dbSource).toContain('Date.now() - lastArchiveExpiredDataAt < 60_000');
  });

  it("includes admin-only analytics and category flow management on the admin page", () => {
    expect(adminPageSource).toContain("管理後台僅限 admin 查看");
    expect(adminPageSource).toContain("全員 KPI 進度");
    expect(adminPageSource).toContain("目前查看區間");
    expect(adminPageSource).toContain("kpiFilterStartDate");
    expect(adminPageSource).toContain("kpiFilterEndDate");
    expect(adminPageSource).toContain("lastLoadedKpiRangeRef");
    expect(adminPageSource).toContain("shouldSyncDraftRange");
    expect(adminPageSource).toContain("handleApplyKpiFilter");
    expect(adminPageSource).toContain("handleResetKpiFilter");
    expect(adminPageSource).toContain("套用 KPI 篩選");
    expect(adminPageSource).toContain("重設為當月");
    expect(adminPageSource).toContain("匯入到各節點平均天數");
    expect(adminPageSource).toContain("歷史樣本數");
    expect(adminPageSource).toContain("若要看目前待入庫商品，請以待入庫站點頁清單為準");
    expect(adminPageSource).toContain("待入庫週期摘要");
    expect(adminPageSource).toContain("品類設定");
    expect(adminPageSource).toContain("此品類需要經過的節點");
    expect(adminPageSource).toContain("toggleCategoryFlowStation");
    expect(adminPageSource).toContain("trpc.admin.saveAllSettings.useMutation");
    expect(adminPageSource).toContain("categoryFlowCategorySearch");
    expect(adminPageSource).toContain("categoryFlowBrandSearch");
    expect(adminPageSource).toContain("搜尋商品類別，例如 智慧手機");
    expect(adminPageSource).toContain("搜尋品牌，例如 Apple");
    expect(adminPageSource).toContain("filteredFlowCategories");
    expect(adminPageSource).toContain("查無符合目前商品類別與品牌搜尋條件的品類設定");
    expect(adminPageSource).toContain("快速複製現有品類流程");
    expect(adminPageSource).toContain("categoryFlowCopyTargets");
    expect(adminPageSource).toContain("handleCopyCategoryFlow");
    expect(adminPageSource).toContain("[targetCategoryId]: [...sourceFlow]");
    expect(adminPageSource).toContain("[sourceCategoryId]: \"\"");
    expect(adminPageSource).toContain("複製流程到目標品類");
    expect(adminPageSource).toContain("複製到目標品類");
    expect(adminPageSource).toContain("儲存全部設定");
    expect(adminPageSource).toContain("handleSaveAllSettings");
    expect(adminPageSource).toContain("全部儲存成功，已更新站點規則、產能設定、功能表設定與品類流程");
    expect(adminPageSource).toContain("categoryFlows: categories.map");
    expect(adminPageSource).not.toContain("儲存流程設定");
    expect(adminPageSource).not.toContain("儲存產能");
    expect(adminPageSource).not.toContain("儲存功能表項目");
    expect(adminPageSource).toContain("功能表設定");
    expect(adminPageSource).toContain('const MANAGEMENT_VIEWER_ROLES = ["supervisor", "manager", "admin"]');
    expect(adminPageSource).toContain('allowedRoles: MANAGEMENT_VIEWER_ROLES');
    expect(adminPageSource).toContain("B 站軟測故障狀態");
    expect(adminPageSource).toContain("C 站螢幕狀態");
    expect(adminPageSource).toContain("C 站機身外觀");
    expect(adminPageSource).toContain("C 站鏡頭狀態");
    expect(adminPageSource).toContain("品名管理");
    expect(adminPageSource).toContain('label: "資料工具", path: "/admin/tools"');
    expect(adminPageSource).toContain('label: "庫存異動紀錄", path: "/admin/inventory-history"');
    expect(adminPageSource).toContain("庫存異動紀錄");
    expect(adminPageSource).toContain("匯入時間");
    expect(adminPageSource).toContain("待入庫時間");
    expect(adminPageSource).toContain("入庫時間");
    expect(adminPageSource).toContain("匯入批次備份／還原");
    expect(adminPageSource).toContain("trpc.admin.importBackups.useQuery");
    expect(adminPageSource).toContain("trpc.admin.createImportBackup.useMutation");
    expect(adminPageSource).toContain("trpc.admin.restoreImportBackup.useMutation");
    expect(adminPageSource).toContain("預覽筆數");
    expect(adminPageSource).toContain("目前 DB 現有筆數");
    expect(adminPageSource).toContain("刪除指定採購單的用途");
    expect(adminPageSource).toContain("商品批號／序號追蹤");
    expect(adminPageSource).toContain("trpc.admin.productTrace.useQuery");
    expect(adminPageSource).toContain("handleProductTraceSearch");
    expect(adminPageSource).toContain("平均單站耗時");
    expect(adminPageSource).toContain("異常高亮");
    expect(adminPageSource).toContain("事件紀錄");
    expect(adminPageSource).toContain("trpc.admin.createProductNameOption.useMutation");
    expect(adminPageSource).toContain("trpc.admin.deleteProductNameOption.useMutation");
  });
});
